name: animorph_voice_app
description: A voice translator for animals
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.6.3
  permission_handler: ^11.0.1
  speech_to_text: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

